spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexuspay_dev
    username: postgres
    password: postgres
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    com.nexuspay: DEBUG
    org.hibernate.SQL: DEBUG
